"area-www":
  - any:
      [
        "apps/www/**",
        "packages/ui/**",
        "packages/utils/**",
        ".github/workflows/www-ci.yml",
        "package.json",
      ]

"area-dash":
  - any:
      [
        "apps/dash/**",
        "packages/ui/**",
        "packages/utils/**",
        "packages/auth/**",
        "packages/api/**",
        "packages/db/**",
        ".github/workflows/dash-ci.yml",
        "package.json",
      ]

"area-service":
  - any:
      [
        "apps/service/**",
        "packages/db/**",
        ".github/workflows/service-ci.yml",
        "package.json",
      ]
