"area-www":
  - any:
      [
        "apps/www/**",
        "packages/ui/**",
        "packages/utils/**",
        ".github/workflows/www-ci.yml",
        "package.json",
      ]

"area-dash":
  - any:
      [
        "apps/dash/**",
        "packages/ui/**",
        "packages/utils/**",
        "packages/auth/**",
        "packages/api/**",
        "packages/db/**",
        ".github/workflows/dash-ci.yml",
        "package.json",
      ]

"area-service":
  - any:
      [
        "apps/service/**",
        "packages/db/**",
        ".github/workflows/service-ci.yml",
        "package.json",
      ]

"area-auth":
  - any:
      [
        "apps/auth/**",
        "packages/auth/**",
        ".github/workflows/auth-ci.yml",
        "package.json",
      ]

"area-ai":
  - any:
      [
        "apps/ai/**",
        "packages/ai/**",
        ".github/workflows/ai-ci.yml",
        "package.json",
      ]

"area-gateway":
  - any: ["apps/gateway/**", "infra/railway/gateway.json"]
