version: "3.9"

services:
  app:
    build:
      context: .
      args:
        GH_PUBLIC_TOKEN: ${GH_PUBLIC_TOKEN}
        GOOGLE_API_KEY: ${GOOGLE_API_KEY}
        NEXT_PUBLIC_RE_CAPTCHA_KEY: ${NEXT_PUBLIC_RE_CAPTCHA_KEY}
        ZEABUR_URL: ${ZEABUR_URL}
        RAILWAY_STATIC_URL: ${RAILWAY_STATIC_URL}
        SENDGRID_KEY: ${SENDGRID_KEY}
        SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
        SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    ports:
      - "8080:8080"

#    environment:
#      - NODE_ENV=production
#      - GH_PUBLIC_TOKEN=${GH_PUBLIC_TOKEN}
#      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
#      - ZEABUR_URL=${ZEABUR_URL}
#      - RAILWAY_STATIC_URL=${RAILWAY_STATIC_URL}
#      - SENDGRID_KEY=${SENDGRID_KEY}
#      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
#      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}

    restart: always
