packages:
  - apps/*
  - packages/*
  - services/*
  - toolings/**/*
  - tests/*

catalog:
  '@t3-oss/env-core': ^0.13.10
  '@t3-oss/env-nextjs': ^0.13.10
  '@types/lodash': ^4.17.23
  '@types/node': 25.3.0
  better-all: 0.0.7
  bun-types: ^1.3.9
  client-only: ^0.0.1
  dayjs: ^1.11.19
  graphql-request: ^7.4.0
  ky: ^1.14.3
  lodash: ^4.17.23
  server-only: ^0.0.1
  superjson: 2.2.6
  tsdown: 0.20.3
  typescript: ^5.9.3
  zod: 4.3.6

catalogs:
  ai:
    '@ai-sdk/anthropic': 3.0.45
    '@ai-sdk/deepseek': 2.0.20
    '@ai-sdk/google': 3.0.30
    '@ai-sdk/openai': 3.0.30
    '@ai-sdk/react': 3.0.94
    '@anthropic-ai/sdk': 0.77.0
    '@google/genai': 1.42.0
    ai: 6.0.92
    ollama: 0.6.3
    openai: 6.22.0
  better-auth:
    '@better-auth/passkey': 1.4.18
    better-auth: 1.4.18
  chiastack:
    '@chiastack/tsconfig': 2.1.2
    '@chiastack/ui': 1.2.0
  drizzle:
    drizzle-kit: beta
    drizzle-orm: beta
  fumadocs:
    '@fumadocs/mdx-remote': 1.4.5
    fumadocs-core: 16.6.3
    fumadocs-mdx: 14.2.7
    fumadocs-ui: 16.6.3
  heroui-v3:
    '@heroui/react': 3.0.0-beta.7
    '@heroui/styles': 3.0.0-beta.7
  hono:
    '@hono/react-renderer': 1.0.1
    '@hono/sentry': 1.2.2
    '@hono/zod-validator': 0.7.6
    hono: 4.12.2
    hono-rate-limiter: 0.5.3
  next:
    '@next/third-parties': 16.1.6
    next: 16.1.6
  orpc:
    '@orpc/client': 1.13.5
    '@orpc/contract': 1.13.5
    '@orpc/server': 1.13.5
    '@orpc/tanstack-query': 1.13.5
  oxc:
    oxfmt: 0.33.0
    oxlint: 1.48.0
  platejs:
    '@platejs/basic-nodes': ^52.0.11
    platejs: ^52.0.17
  radix-ui:
    '@radix-ui/react-accordion': 1.2.12
    '@radix-ui/react-avatar': ^1.1.11
    '@radix-ui/react-collapsible': ^1.1.12
    '@radix-ui/react-dialog': ^1.1.15
    '@radix-ui/react-dropdown-menu': ^2.1.16
    '@radix-ui/react-hover-card': ^1.1.15
    '@radix-ui/react-label': ^2.1.8
    '@radix-ui/react-navigation-menu': ^1.2.14
    '@radix-ui/react-popover': ^1.1.15
    '@radix-ui/react-progress': ^1.1.8
    '@radix-ui/react-separator': ^1.1.8
    '@radix-ui/react-slot': ^1.2.4
    '@radix-ui/react-tabs': ^1.1.13
    '@radix-ui/react-tooltip': ^1.2.8
  react-is:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    babel-plugin-react-compiler: 1.0.0
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwindcss:
    '@tailwindcss/postcss': 4.2.0
    postcss: 8.5.6
    tailwindcss: 4.2.0
    tailwind-scrollbar: ^4.0.2
  tanstack:
    '@tanstack/react-pacer': 0.20.0
    '@tanstack/react-query': 5.90.21
    '@tanstack/react-query-devtools': 5.91.3
  testing-library:
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/react': 16.3.2
    '@testing-library/user-event': 14.6.1
    '@vitejs/plugin-react-swc': 4.2.3
    '@vitest/coverage-v8': 4.0.18
    '@vitest/ui': 4.0.18
    jest-extended: 7.0.0
    vitest: 4.0.18
  ui:
   class-variance-authority: ^0.7.1
   clsx: ^2.1.1
   cobe: ^0.6.5
   cmdk: 1.1.1
   immer: ^11.1.4
   katex: ^0.16.28
   lucide-react: ^0.575.0
   motion: ^12.34.2
   next-themes: ^0.4.6
   nuqs: ^2.8.8
   react-medium-image-zoom: ^5.4.0
   schema-dts: 1.1.5
   shiki: ^3.22.0
   sonner: 2.0.7
   tailwind-merge: ^3.5.0
   usehooks-ts: ^3.1.1
   vaul: ^1.1.2
   zustand: 5.0.11

linkWorkspacePackages: true

strictPeerDependencies: false
