packages:
  - "apps/*"
  - "packages/*"
  - "toolings/**/*"
  - "tests/*"

catalog:
  "@tanstack/react-query": ^5.75.2
  "@trpc/client": ^11.1.2
  "@trpc/react-query": ^11.1.2
  "@trpc/server": ^11.1.2
  "@trpc/next": ^11.1.2
  eslint: ^9.26.0
  typescript: ^5.8.3
  tailwindcss: 4.1.5
  fumadocs-core: 15.2.13
  fumadocs-ui: 15.2.13
  "@fumadocs/mdx-remote": 1.3.0
  fumadocs-mdx: 11.6.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.20
    "@types/react-dom": ^18.3.7
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": 19.1.2
    "@types/react-dom": 19.1.3
    "babel-plugin-react-compiler": 19.1.0-rc.1
  triggerdotdev:
    "@trigger.dev/core": 3.3.17
    "@trigger.dev/sdk": 3.3.17
    "@trigger.dev/build": 3.3.17
  heroui:
    "@heroui/react": beta
    "@heroui/theme": beta
