packages:
  - apps/*
  - packages/*
  - services/*
  - toolings/**/*
  - tests/*

catalog:
  '@t3-oss/env-core': ^0.13.10
  '@t3-oss/env-nextjs': ^0.13.10
  '@types/lodash': ^4.17.23
  '@types/node': 25.1.0
  better-all: 0.0.5
  bun-types: ^1.3.7
  client-only: ^0.0.1
  dayjs: ^1.11.19
  graphql-request: ^7.4.0
  ky: ^1.14.3
  lodash: ^4.17.23
  server-only: ^0.0.1
  superjson: 2.2.6
  tsdown: 0.20.1
  typescript: ^5.9.3
  zod: 4.3.6

catalogs:
  better-auth:
    '@better-auth/passkey': 1.4.17
    better-auth: 1.4.17
  chiastack:
    '@chiastack/tsconfig': 2.1.1
  drizzle:
    drizzle-kit: 1.0.0-beta.12-a5629fb
    drizzle-orm: 1.0.0-beta.12-a5629fb
    drizzle-zod: 1.0.0-beta.12-a5629fb
  fumadocs:
    '@fumadocs/mdx-remote': 1.4.4
    fumadocs-core: 16.4.9
    fumadocs-mdx: 14.2.6
    fumadocs-ui: 16.4.9
  heroui:
    '@heroui/react': 2.8.7
    '@heroui/theme': 2.4.25
  heroui-v3:
    '@heroui/react': 3.0.0-beta.5
    '@heroui/styles': 3.0.0-beta.5
  next:
    '@next/third-parties': 16.1.6
    next: 16.1.6
  orpc:
    '@orpc/client': 1.13.4
    '@orpc/contract': 1.13.4
    '@orpc/server': 1.13.4
    '@orpc/tanstack-query': 1.13.4
  oxc:
    oxfmt: 0.27.0
    oxlint: 1.42.0
  react-is:
    '@types/react': ^19.2.10
    '@types/react-dom': ^19.2.3
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwindcss:
    '@tailwindcss/postcss': 4.1.18
    tailwindcss: 4.1.18
  tanstack:
    '@tanstack/react-pacer': 0.19.4
    '@tanstack/react-query': 5.90.20
    '@tanstack/react-query-devtools': 5.91.2
  testing-library:
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/react': 16.3.2
    '@testing-library/user-event': 14.6.1
    '@vitejs/plugin-react-swc': 4.2.2
    '@vitest/coverage-v8': 4.0.18
    '@vitest/ui': 4.0.18
    jest-extended: 7.0.0
    vitest: 4.0.18

linkWorkspacePackages: true

strictPeerDependencies: false
