packages:
  - apps/*
  - packages/*
  - toolings/**/*
  - tests/*

catalog:
  '@fumadocs/mdx-remote': 1.3.4
  '@tanstack/react-query': ^5.82.0
  '@trpc/client': ^11.4.3
  '@trpc/next': ^11.4.3
  '@trpc/react-query': ^11.4.3
  '@trpc/server': ^11.4.3
  eslint: ^9.31.0
  fumadocs-core: 15.6.3
  fumadocs-mdx: 11.6.11
  fumadocs-ui: 15.6.3
  tailwindcss: 4.1.11
  typescript: ^5.8.3

catalogs:
  heroui:
    '@heroui/react': 2.8.0-beta.15
    '@heroui/theme': 2.4.18-beta.7
  react18:
    '@types/react': ^18.3.23
    '@types/react-dom': ^18.3.7
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
    babel-plugin-react-compiler: 19.1.0-rc.2
    react: ^19.1.0
    react-dom: ^19.1.0
  triggerdotdev:
    '@trigger.dev/build': 3.3.17
    '@trigger.dev/core': 3.3.17
    '@trigger.dev/sdk': 3.3.17
