packages:
  - apps/*
  - packages/*
  - toolings/**/*
  - tests/*

catalog:
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@tanstack/react-query': ^5.90.5
  '@types/lodash': ^4.17.20
  '@types/node': 22.18.13
  bun-types: ^1.3.1
  client-only: ^0.0.1
  dayjs: ^1.11.19
  graphql-request: ^7.3.1
  ky: ^1.13.0
  lodash: ^4.17.21
  server-only: ^0.0.1
  superjson: 2.2.5
  typescript: ^5.9.3
  zod: ^4.1.12

catalogs:
  eslint:
    '@eslint/js': 9.38.0
    eslint: 9.38.0
  fumadocs:
    '@fumadocs/mdx-remote': 1.4.3
    fumadocs-core: 16.0.6
    fumadocs-mdx: 13.0.3
    fumadocs-ui: 16.0.6
  heroui:
    '@heroui/react': 2.8.5
    '@heroui/theme': 2.4.23
  next:
    '@next/bundle-analyzer': 16.0.1
    '@next/eslint-plugin-next': 16.0.1
    '@next/third-parties': 16.0.1
    next: 16.0.1
  react18:
    '@types/react': ^18.3.26
    '@types/react-dom': ^18.3.7
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: ^19.2.0
    react-dom: ^19.2.0
  tailwindcss:
    '@tailwindcss/postcss': 4.1.16
    tailwindcss: 4.1.16
  triggerdotdev:
    '@trigger.dev/build': 4.0.5
    '@trigger.dev/core': 4.0.5
    '@trigger.dev/sdk': 4.0.5
  trpc:
    '@trpc/client': 11.7.1
    '@trpc/next': 11.7.1
    '@trpc/react-query': 11.7.1
    '@trpc/server': 11.7.1

linkWorkspacePackages: true

strictPeerDependencies: false
