packages:
  - "apps/*"
  - "packages/*"
  - "toolings/**/*"
  - "tests/*"

catalog:
  "@tanstack/react-query": ^5.67.2
  "@trpc/client": ^11.0.0-rc.824
  "@trpc/react-query": ^11.0.0-rc.824
  "@trpc/server": ^11.0.0-rc.824
  "@trpc/next": ^11.0.0-rc.824
  eslint: ^9.22.0
  typescript: ^5.8.2
  tailwindcss: 3.4.17
  fumadocs-core: 14.7.7
  fumadocs-ui: 14.7.7
  "@fumadocs/mdx-remote": 1.2.0
  fumadocs-mdx: 11.5.6

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.18
    "@types/react-dom": ^18.3.5
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.10
    "@types/react-dom": 19.0.4
    "babel-plugin-react-compiler": beta
  tailwindcss3:
    tailwindcss: 3.4.17
  tailwindcss4:
    tailwindcss: 4.0.9
  triggerdotdev:
    "@trigger.dev/core": 3.3.17
    "@trigger.dev/sdk": 3.3.17
    "@trigger.dev/build": 3.3.17