packages:
  - apps/*
  - packages/*
  - services/*
  - toolings/**/*
  - tests/*

catalog:
  '@t3-oss/env-core': ^0.13.10
  '@t3-oss/env-nextjs': ^0.13.10
  '@types/lodash': ^4.17.23
  '@types/node': 25.0.10
  better-all: 0.0.5
  bun-types: ^1.3.6
  client-only: ^0.0.1
  dayjs: ^1.11.19
  graphql-request: ^7.4.0
  ky: ^1.14.2
  lodash: ^4.17.23
  server-only: ^0.0.1
  superjson: 2.2.6
  tsdown: 0.20.0
  typescript: ^5.9.3
  zod: 4.3.5

catalogs:
  better-auth:
    '@better-auth/passkey': 1.4.17
    better-auth: 1.4.17
  chiastack:
    '@chiastack/eslint': 2.0.4
    '@chiastack/tsconfig': 2.1.1
  drizzle:
    drizzle-kit: beta
    drizzle-orm: beta
    drizzle-zod: beta
  eslint:
    eslint: 9.39.2
  fumadocs:
    '@fumadocs/mdx-remote': 1.4.4
    fumadocs-core: 16.4.7
    fumadocs-mdx: 14.2.6
    fumadocs-ui: 16.4.7
  heroui:
    '@heroui/react': 2.8.7
    '@heroui/theme': 2.4.25
  next:
    '@next/third-parties': 16.1.4
    next: 16.1.4
  orpc:
    '@orpc/client': 1.13.4
    '@orpc/contract': 1.13.4
    '@orpc/server': 1.13.4
    '@orpc/tanstack-query': 1.13.4
  react-is:
    '@types/react': ^19.2.9
    '@types/react-dom': ^19.2.3
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: ^19.2.3
    react-dom: ^19.2.3
  tailwindcss:
    '@tailwindcss/postcss': 4.1.18
    tailwindcss: 4.1.18
  tanstack:
    '@tanstack/react-pacer': 0.19.3
    '@tanstack/react-query': 5.90.19
  testing-library:
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/react': 16.3.2
    '@testing-library/user-event': 14.6.1
    '@vitejs/plugin-react-swc': 4.2.2
    '@vitest/coverage-v8': 4.0.17
    '@vitest/ui': 4.0.17
    jest-extended: 7.0.0
    vitest: 4.0.17

linkWorkspacePackages: true

strictPeerDependencies: false
