packages:
  - "apps/*"
  - "packages/*"
  - "toolings/**/*"
  - "tests/*"

catalog:
  "@tanstack/react-query": ^5.61.3
  "@trpc/client": ^11.0.0-rc.643
  "@trpc/react-query": ^11.0.0-rc.643
  "@trpc/server": ^11.0.0-rc.643
  "@trpc/next": ^11.0.0-rc.643
  eslint: ^9.15.0
  typescript: ^5.7.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  react19:
    react: rc
    react-dom: rc
    "@types/react": npm:types-react@rc
    "@types/react-dom": npm:types-react-dom@rc
    "babel-plugin-react-compiler": beta
