packages:
  - apps/*
  - packages/*
  - toolings/**/*
  - tests/*

catalog:
  '@fumadocs/mdx-remote': 1.4.0
  '@tanstack/react-query': ^5.87.1
  '@trpc/client': ^11.5.1
  '@trpc/next': ^11.5.1
  '@trpc/react-query': ^11.5.1
  '@trpc/server': ^11.5.1
  eslint: ^9.35.0
  fumadocs-core: 15.7.10
  fumadocs-mdx: 11.9.0
  fumadocs-ui: 15.7.10
  tailwindcss: 4.1.13
  typescript: ^5.9.2

catalogs:
  heroui:
    '@heroui/react': 2.8.4
    '@heroui/theme': 2.4.22
  react18:
    '@types/react': ^18.3.24
    '@types/react-dom': ^18.3.7
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: ^19.1.1
    react-dom: ^19.1.1
  triggerdotdev:
    '@trigger.dev/build': 4.0.2
    '@trigger.dev/core': 4.0.2
    '@trigger.dev/sdk': 4.0.2
