packages:
  - "apps/*"
  - "packages/*"
  - "toolings/**/*"
  - "tests/*"

catalog:
  "@tanstack/react-query": ^5.59.0
  "@trpc/client": ^11.0.0-rc.553
  "@trpc/react-query": ^11.0.0-rc.553
  "@trpc/server": ^11.0.0-rc.553
  "@trpc/next": ^11.0.0-rc.553
  eslint: ^9.11.1
  typescript: ^5.6.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.10
    "@types/react-dom": ^18.3.0
