packages:
  - "apps/*"
  - "packages/*"
  - "toolings/**/*"
  - "tests/*"

catalog:
  "@tanstack/react-query": ^5.59.16
  "@trpc/client": ^11.0.0-rc.604
  "@trpc/react-query": ^11.0.0-rc.604
  "@trpc/server": ^11.0.0-rc.604
  "@trpc/next": ^11.0.0-rc.604
  eslint: ^9.13.0
  typescript: ^5.6.3

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  react19:
    react: rc
    react-dom: rc
    "@types/react": npm:types-react@rc
    "@types/react-dom": npm:types-react-dom@rc
    "babel-plugin-react-compiler": beta
