packages:
  - "apps/*"
  - "packages/*"
  - "toolings/**/*"
  - "tests/*"

catalog:
  "@tanstack/react-query": ^5.62.7
  "@trpc/client": ^11.0.0-rc.660
  "@trpc/react-query": ^11.0.0-rc.660
  "@trpc/server": ^11.0.0-rc.660
  "@trpc/next": ^11.0.0-rc.660
  eslint: ^9.17.0
  typescript: ^5.7.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.0
    "@types/react-dom": 19.0.0
    "babel-plugin-react-compiler": beta
