packages:
  - apps/*
  - packages/*
  - toolings/**/*
  - tests/*

catalog:
  '@fumadocs/mdx-remote': 1.4.2
  '@tanstack/react-query': ^5.90.5
  '@trpc/client': ^11.6.0
  '@trpc/next': ^11.6.0
  '@trpc/react-query': ^11.6.0
  '@trpc/server': ^11.6.0
  eslint: ^9.37.0
  fumadocs-core: 15.8.5
  fumadocs-mdx: 12.0.3
  fumadocs-ui: 15.8.5
  tailwindcss: 4.1.14
  typescript: ^5.9.3

catalogs:
  heroui:
    '@heroui/react': 2.8.5
    '@heroui/theme': 2.4.23
  react18:
    '@types/react': ^18.3.26
    '@types/react-dom': ^18.3.7
    react: 18.3.1
    react-dom: 18.3.1
  react19:
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    babel-plugin-react-compiler: 19.1.0-rc.3
    react: ^19.2.0
    react-dom: ^19.2.0
  triggerdotdev:
    '@trigger.dev/build': 4.0.4
    '@trigger.dev/core': 4.0.4
    '@trigger.dev/sdk': 4.0.4
