packages:
  - "apps/*"
  - "packages/*"
  - "toolings/**/*"
  - "tests/*"

catalog:
  "@tanstack/react-query": ^5.66.0
  "@trpc/client": ^11.0.0-rc.730
  "@trpc/react-query": ^11.0.0-rc.730
  "@trpc/server": ^11.0.0-rc.730
  "@trpc/next": ^11.0.0-rc.730
  eslint: ^9.19.0
  typescript: ^5.7.3
  tailwindcss: 4.0.3
  fumadocs-core: 15.0.1
  fumadocs-ui: 15.0.1

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.18
    "@types/react-dom": ^18.3.5
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.8
    "@types/react-dom": 19.0.3
    "babel-plugin-react-compiler": beta
