packages:
  - "apps/*"
  - "packages/*"
  - "toolings/**/*"
  - "tests/*"

catalog:
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.3
  "@trpc/react-query": ^11.4.3
  "@trpc/server": ^11.4.3
  "@trpc/next": ^11.4.3
  eslint: ^9.29.0
  typescript: ^5.8.3
  tailwindcss: 4.1.10
  fumadocs-core: 15.5.3
  fumadocs-ui: 15.5.3
  "@fumadocs/mdx-remote": 1.3.3
  fumadocs-mdx: 11.6.9

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.21
    "@types/react-dom": ^18.3.7
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": 19.1.8
    "@types/react-dom": 19.1.6
    "babel-plugin-react-compiler": 19.1.0-rc.2
  triggerdotdev:
    "@trigger.dev/core": 3.3.17
    "@trigger.dev/sdk": 3.3.17
    "@trigger.dev/build": 3.3.17
  heroui:
    "@heroui/react": beta
    "@heroui/theme": beta
