packages:
  - apps/*
  - packages/*
  - services/*
  - toolings/**/*
  - tests/*

catalog:
  '@t3-oss/env-core': ^0.13.10
  '@t3-oss/env-nextjs': ^0.13.10
  '@types/lodash': ^4.17.24
  '@types/node': 25.5.0
  better-all: 0.0.7
  bun-types: ^1.3.11
  client-only: ^0.0.1
  dayjs: ^1.11.20
  graphql-request: ^7.4.0
  ky: ^1.14.3
  lodash: ^4.17.23
  server-only: ^0.0.1
  superjson: 2.2.6
  tsdown: 0.21.4
  typescript: ^5.9.3
  zod: 4.3.6

catalogs:
  ai:
    '@ai-sdk/anthropic': 3.0.63
    '@ai-sdk/deepseek': 2.0.26
    '@ai-sdk/google': 3.0.52
    '@ai-sdk/openai': 3.0.47
    '@ai-sdk/react': 3.0.136
    '@anthropic-ai/sdk': 0.80.0
    '@google/genai': 1.46.0
    ai: 6.0.134
    ollama: 0.6.3
    openai: 6.32.0
  better-auth:
    '@better-auth/api-key': 1.5.5
    '@better-auth/passkey': 1.5.5
    better-auth: 1.5.5
  chiastack:
    '@chiastack/oxlint': 1.1.0
    '@chiastack/tsconfig': 2.1.2
    '@chiastack/ui': 1.2.2
  drizzle:
    drizzle-kit: 1.0.0-beta.18-7eb39f0
    drizzle-orm: 1.0.0-beta.18-7eb39f0
  fumadocs:
    '@fumadocs/mdx-remote': 1.4.6
    fumadocs-core: 16.7.4
    fumadocs-mdx: 14.2.11
    fumadocs-ui: 16.7.4
  heroui-v3:
    '@heroui/react': 3.0.1
    '@heroui/styles': 3.0.1
  hono:
    '@hono/react-renderer': 1.0.1
    '@hono/sentry': 1.2.2
    '@hono/zod-validator': 0.7.6
    hono: 4.12.8
    hono-rate-limiter: 0.5.3
  next:
    '@next/third-parties': 16.2.1
    next: 16.2.1
  orpc:
    '@orpc/client': 1.13.9
    '@orpc/contract': 1.13.9
    '@orpc/server': 1.13.9
    '@orpc/tanstack-query': 1.13.9
  oxc:
    oxfmt: 0.41.0
    oxlint: 1.56.0
  platejs:
    '@platejs/basic-nodes': ^52.0.11
    platejs: ^52.3.4
  radix-ui:
    '@radix-ui/react-accordion': 1.2.12
    '@radix-ui/react-avatar': ^1.1.11
    '@radix-ui/react-collapsible': ^1.1.12
    '@radix-ui/react-dialog': ^1.1.15
    '@radix-ui/react-dropdown-menu': ^2.1.16
    '@radix-ui/react-hover-card': ^1.1.15
    '@radix-ui/react-label': ^2.1.8
    '@radix-ui/react-navigation-menu': ^1.2.14
    '@radix-ui/react-popover': ^1.1.15
    '@radix-ui/react-progress': ^1.1.8
    '@radix-ui/react-separator': ^1.1.8
    '@radix-ui/react-slot': ^1.2.4
    '@radix-ui/react-tabs': ^1.1.13
    '@radix-ui/react-tooltip': ^1.2.8
  react-is:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    babel-plugin-react-compiler: 1.0.0
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwindcss:
    '@tailwindcss/postcss': 4.2.2
    postcss: 8.5.8
    tailwind-scrollbar: ^4.0.2
    tailwindcss: 4.2.2
  tanstack:
    '@tanstack/react-pacer': 0.20.0
    '@tanstack/react-query': 5.94.5
    '@tanstack/react-query-devtools': 5.94.5
  testing-library:
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/react': 16.3.2
    '@testing-library/user-event': 14.6.1
    '@vitejs/plugin-react-swc': 4.3.0
    '@vitest/coverage-v8': 4.1.0
    '@vitest/ui': 4.1.0
    jest-extended: 7.0.0
    vitest: 4.1.0
  ui:
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: 1.1.1
    cobe: ^2.0.1
    immer: ^11.1.4
    katex: ^0.16.40
    lucide-react: ^0.577.0
    motion: ^12.38.0
    next-themes: ^0.4.6
    nuqs: ^2.8.9
    react-medium-image-zoom: ^5.4.1
    schema-dts: 1.1.5
    shiki: ^4.0.2
    sonner: 2.0.7
    tailwind-merge: ^3.5.0
    usehooks-ts: ^3.1.1
    vaul: ^1.1.2
    zustand: 5.0.12

linkWorkspacePackages: true

strictPeerDependencies: false
