packages:
  - "apps/*"
  - "packages/*"
  - "toolings/**/*"
  - "tests/*"

catalog:
  "@tanstack/react-query": ^5.51.24
  "@trpc/client": ^11.0.0-rc.482
  "@trpc/react-query": ^11.0.0-rc.482
  "@trpc/server": ^11.0.0-rc.482
  "@trpc/next": ^11.0.0-rc.482
  eslint: ^9.9.0
  typescript: ^5.5.4

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
