import type { ReactNode } from "react";
import Menu from "./menu";
import { Page } from "ui";

export const metadata = {
  title: "Next App",
  description: "Generated by @chia-stack/nextjs-app template",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Menu />
      <Page>{children}</Page>
    </>
  );
}
