import {
  SiFirebase,
  SiJavascript,
  SiTypescript,
  SiNextdotjs,
  SiJava,
  SiPhp,
  SiMysql,
  SiMongodb,
  SiNestjs,
  SiLaravel,
  SiVuedotjs,
  SiTailwindcss,
  SiVisualstudiocode,
  SiJetbrains,
  SiGit,
  SiDocker,
  SiGithubactions,
  SiGooglecloud,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiAdobepremierepro,
  SiReact,
  SiAdobeindesign,
} from "react-icons/si";

export const Chia = {
  name: "Chia1104",
  chineseName: "俞又嘉",
  fullName: "Yu Chia, Yu",
  title: "Web Developer",
  email: "yuyuchia7423@gmail.com",
  phone: "+886 0970227360",
  content:
    "Computer science developer with a passion for web development and data analysis.",
  link: {
    github: "https://github.com/Chia1104",
    linkedin:
      "https://www.linkedin.com/in/%E5%8F%88%E5%98%89-%E4%BF%9E-889664230",
    instagram: "https://www.instagram.com/chia_1104",
    youtube_playlist:
      "https://www.youtube.com/playlist?list=PL7XkMe5ddX9Napk5747U6SIOAqWJBsqVM",
    google_photos: "https://photos.app.goo.gl/J1FobfgynJKW84Dm6",
  },
  technologies: {
    languages: [
      {
        name: "JavaScript",
        level: "Advanced",
        link: "https://www.javascript.com/",
        icon: SiJavascript,
      },
      {
        name: "TypeScript",
        level: "Basic",
        link: "https://www.typescriptlang.org/",
        icon: SiTypescript,
      },
      {
        name: "Java",
        level: "Advanced",
        link: "https://www.java.com/",
        icon: SiJava,
      },
      {
        name: "PHP",
        level: "Advanced",
        link: "https://www.php.net/",
        icon: SiPhp,
      },
    ],
    web_frameworks: [
      {
        name: "ReactJS",
        level: "Advanced",
        link: "https://reactjs.org/",
        icon: SiReact,
      },
      {
        name: "NextJS",
        level: "Advanced",
        link: "https://nextjs.org/",
        icon: SiNextdotjs,
      },
      {
        name: "VueJS",
        level: "Basic",
        link: "https://vuejs.org/",
        icon: SiVuedotjs,
      },
      {
        name: "TailwindCSS",
        level: "Advanced",
        link: "https://tailwindcss.com/",
        icon: SiTailwindcss,
      },
      {
        name: "Laravel",
        level: "Advanced",
        link: "https://laravel.com/",
        icon: SiLaravel,
      },
      {
        name: "NestJS",
        level: "Advanced",
        link: "https://nestjs.com/",
        icon: SiNestjs,
      },
    ],
    devops: [
      {
        name: "Docker",
        level: "Basic",
        link: "https://www.docker.com/",
        icon: SiDocker,
      },
      {
        name: "GitHub Actions",
        level: "Advanced",
        link: "https://github.com/features/actions",
        icon: SiGithubactions,
      },
      {
        name: "GCP",
        level: "Basic",
        link: "https://cloud.google.com/",
        icon: SiGooglecloud,
      },
    ],
    databases: [
      {
        name: "MySQL",
        level: "Basic",
        link: "https://www.mysql.com/",
        icon: SiMysql,
      },
      {
        name: "MongoDB",
        level: "Basic",
        link: "https://www.mongodb.com/",
        icon: SiMongodb,
      },
      {
        name: "Firebase",
        level: "Advanced",
        link: "https://firebase.google.com/",
        icon: SiFirebase,
      },
    ],
    design: [
      {
        name: "Photoshop",
        level: "Basic",
        link: "https://www.adobe.com/tw/products/photoshop.html",
        icon: SiAdobephotoshop,
      },
      {
        name: "Illustrator",
        level: "Basic",
        link: "https://www.adobe.com/tw/products/illustrator.html",
        icon: SiAdobeillustrator,
      },
      {
        name: "InDesign",
        level: "Basic",
        link: "https://www.adobe.com/tw/products/indesign.html",
        icon: SiAdobeindesign,
      },
      {
        name: "Premiere Pro",
        level: "Basic",
        link: "https://www.adobe.com/tw/products/premiere.html",
        icon: SiAdobepremierepro,
      },
    ],
    other_tools: [
      {
        name: "Git",
        level: "Advanced",
        link: "https://git-scm.com/",
        icon: SiGit,
      },
      {
        name: "VS Code",
        level: "Advanced",
        link: "https://code.visualstudio.com/",
        icon: SiVisualstudiocode,
      },
      {
        name: "JetBrains IDE",
        level: "Advanced",
        link: "https://www.jetbrains.com/",
        icon: SiJetbrains,
      },
    ],
  },
  location: "Taipei, Taiwan",
  bio: "Hello there",
  company: "CGU, IM",
  resume: [
    {
      title: "Work Experience",
      company: "WANIN",
      duration: "2022 - Now",
      location: "Taipei, Taiwan",
      work: "Web Development",
      link: "https://www.wanin.tw/",
    },
    {
      title: "Education",
      company: "CGU, IM",
      duration: "2018 - 2022",
      location: "Taipei, Taiwan",
      work: "MIS, Java, Python, MySQL, Computer Science, System Design",
      link: "https://im.cgu.edu.tw/",
    },
  ],
};
