import {
  SiFirebase,
  SiTypescript,
  SiNextdotjs,
  SiJava,
  SiPhp,
  SiPostgresql,
  SiMongodb,
  SiNestjs,
  SiLaravel,
  SiVuedotjs,
  SiTailwindcss,
  SiVisualstudiocode,
  SiJetbrains,
  SiGit,
  SiDocker,
  SiGithubactions,
  SiGooglecloud,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiAdobepremierepro,
  SiReact,
} from "react-icons/si";

export const Chia = {
  name: "Chia1104" as const,
  chineseName: "俞又嘉" as const,
  fullName: "Yu Chia, Yu" as const,
  title: "Full Stack Engineer" as const,
  email: "yuyuchia7423@gmail.com" as const,
  phone: "+886 0970227360" as const,
  content:
    "I am Yu Chia, Yu, a full-stack engineer with one year of experience in web development" as const,
  link: {
    github: "https://github.com/Chia1104",
    linkedin:
      "https://www.linkedin.com/in/%E5%8F%88%E5%98%89-%E4%BF%9E-889664230",
    instagram: "https://www.instagram.com/chia_1104",
    youtube_playlist:
      "https://www.youtube.com/playlist?list=PL7XkMe5ddX9Napk5747U6SIOAqWJBsqVM",
    google_photos: "https://photos.app.goo.gl/J1FobfgynJKW84Dm6",
  } as const,
  technologies: {
    languages: [
      {
        name: "TypeScript",
        level: "Advanced",
        link: "https://www.typescriptlang.org/",
        icon: SiTypescript,
      },
      {
        name: "Java",
        level: "Basic",
        link: "https://www.java.com/",
        icon: SiJava,
      },
      {
        name: "PHP",
        level: "Basic",
        link: "https://www.php.net/",
        icon: SiPhp,
      },
    ],
    web_frameworks: [
      {
        name: "ReactJS",
        level: "Advanced",
        link: "https://reactjs.org/",
        icon: SiReact,
      },
      {
        name: "NextJS",
        level: "Advanced",
        link: "https://nextjs.org/",
        icon: SiNextdotjs,
      },
      {
        name: "VueJS",
        level: "Advanced",
        link: "https://vuejs.org/",
        icon: SiVuedotjs,
      },
      {
        name: "TailwindCSS",
        level: "Advanced",
        link: "https://tailwindcss.com/",
        icon: SiTailwindcss,
      },
      {
        name: "Laravel",
        level: "Advanced",
        link: "https://laravel.com/",
        icon: SiLaravel,
      },
      {
        name: "NestJS",
        level: "Advanced",
        link: "https://nestjs.com/",
        icon: SiNestjs,
      },
    ],
    devops: [
      {
        name: "Docker",
        level: "Basic",
        link: "https://www.docker.com/",
        icon: SiDocker,
      },
      {
        name: "GitHub Actions",
        level: "Basic",
        link: "https://github.com/features/actions",
        icon: SiGithubactions,
      },
      {
        name: "GCP",
        level: "Basic",
        link: "https://cloud.google.com/",
        icon: SiGooglecloud,
      },
    ],
    databases: [
      {
        name: "PostgreSQL",
        level: "Basic",
        link: "https://www.mysql.com/",
        icon: SiPostgresql,
      },
      {
        name: "MongoDB",
        level: "Basic",
        link: "https://www.mongodb.com/",
        icon: SiMongodb,
      },
      {
        name: "Firebase",
        level: "Advanced",
        link: "https://firebase.google.com/",
        icon: SiFirebase,
      },
    ],
    design: [
      {
        name: "Photoshop",
        level: "Basic",
        link: "https://www.adobe.com/tw/products/photoshop.html",
        icon: SiAdobephotoshop,
      },
      {
        name: "Illustrator",
        level: "Basic",
        link: "https://www.adobe.com/tw/products/illustrator.html",
        icon: SiAdobeillustrator,
      },
      {
        name: "Premiere Pro",
        level: "Basic",
        link: "https://www.adobe.com/tw/products/premiere.html",
        icon: SiAdobepremierepro,
      },
    ],
    other_tools: [
      {
        name: "Git",
        level: "Advanced",
        link: "https://git-scm.com/",
        icon: SiGit,
      },
      {
        name: "VS Code",
        level: "Advanced",
        link: "https://code.visualstudio.com/",
        icon: SiVisualstudiocode,
      },
      {
        name: "JetBrains IDE",
        level: "Advanced",
        link: "https://www.jetbrains.com/",
        icon: SiJetbrains,
      },
    ],
  },
  location: "Taipei, Taiwan" as const,
  bio: "Hello there" as const,
  company: "LeadBest" as const,
  resume: [
    {
      title: "Work Experience",
      company: "LeadBest",
      duration: "2023-3 - Now",
      location: "Taipei, Taiwan",
      work: "ReactJS, NextJS, TypeScript, GCP",
      link: "https://www.leadbestconsultant.com/",
    },
    {
      title: "Work Experience",
      company: "WANIN",
      duration: "2022-7 - 2023-1",
      location: "Taipei, Taiwan",
      work: "NextJS, VueJS, TailwindCSS, TypeScript, Turborepo, GCP",
      link: "https://www.wanin.tw/",
      detail: [
        "Developed a full-stack project, League Funny, which is a website where users can share posts about their favorite games.",
        "Led the development of the NextJS frontend and backend services, including code review, feature planning, and testing.",
        "Reduced 50% of the development time by using Turborepo to manage multiple repositories.",
        "Developed useful hooks such as useS3ImageUpload and useInfiniteScroll to streamline development.",
        "Led other developers to learn and use new technologies and React features.",
      ],
    },
    {
      title: "Education",
      company: "CGU, IM",
      duration: "2018-6 - 2022-6",
      location: "Taipei, Taiwan",
      work: "MIS, Java, Python, MySQL, Computer Science, System Design",
      link: "https://im.cgu.edu.tw/",
    },
  ],
};
