import "./globals.css";
import type { ReactNode } from "react";
import { getServerSession } from "next-auth";
import authOptions from "@/server/auth/auth-options";
import RootProvider from "./root-provider";

export const metadata = {
  title: "Next App",
  description: "Generated by @chia-stack/nextjs-app template",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className="scrollbar-thin scrollbar-thumb-primary dark:scrollbar-thumb-secondary scrollbar-thumb-rounded-full overflow-x-hidden">
        <RootProvider session={session}>{children}</RootProvider>
      </body>
    </html>
  );
}
