// Action type
// Example
export const BEGIN_REQUEST_EXAMPLE_DATA = 'BEGIN_REQUEST_EXAMPLE_DATA';
export const SUCCESS_REQUEST_EXAMPLE_DATA = 'SUCCESS_REQUEST_EXAMPLE_DATA';
export const FAILURE_REQUEST_EXAMPLE_DATA = 'FAILURE_REQUEST_EXAMPLE_DATA';
