// Action type
// Chia Avatar
export const BEGIN_REQUEST_CHIA_AVATAR = 'BEGIN_REQUEST_CHIA_AVATAR';
export const SUCCESS_REQUEST_CHIA_AVATAR = 'SUCCESS_REQUEST_CHIA_AVATAR';
export const FAILURE_REQUEST_CHIA_AVATAR = 'FAILURE_REQUEST_CHIA_AVATAR';
