import { sql } from "drizzle-orm";
import type { InferSelectModel } from "drizzle-orm";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import {
  bigint,
  bigserial,
  index,
  integer,
  jsonb,
  primaryKey,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import type { JsonObject } from "@chia/utils/json";

import { timestamps, softDelete } from "../libs/common.schema.ts";

import { feeds } from "./contents.schema.ts";
import { locale } from "./enums.ts";
import { agentSchema } from "./table.ts";
import { user } from "./user.schema.ts";

/**
 * Persistence for agent sessions.
 *
 * Every table lives in the `agent` Postgres schema, unprefixed. `session` / `session_entry` /
 * `run` / `tool_approval` are **generic** — every agent kind shares them, discriminated by
 * `session.kind`. Writing-specific state lives in `writing_session` and `writing_draft`.
 *
 * The transcript is a **tree**, not a flat log: `session_entry.parentId` points at
 * the previous entry on the branch and `session.leafEntryId` marks the active leaf.
 * That is what lets the agent rewind ("退回三步用另一個角度重寫") and what pi's
 * `SessionStorage` port expects. `@chia/agent-runtime` implements that port over these
 * tables; the writing-specific `writing_draft` belongs to `@chia/agent-writing`.
 *
 * `writing_draft` is the staging buffer: the agent only ever writes here, and a human
 * promotes it into `feed`/`feed_translation`/`content` through the existing
 * `feeds.create`/`feeds.update` procedures.
 *
 * `memory` is the writing agent's long-term memory, the one table here that outlives a
 * session: sources it read, facts it verified and lessons distilled from the operator's
 * feedback. It is indexed into `resource_chunk` like any other resource.
 *
 * `kind_config` and `task_config` hold the operator's overrides of what the code registers:
 * a kind's defaults for new sessions and a task's model, prompt and sampling parameters. Kinds
 * and tasks themselves stay code; a row only ever narrows or re-points what a definition
 * already allows, and no row means the definition's own values apply.
 *
 * `usage_ledger` is one row per provider call made on a user's behalf — turns and the side jobs
 * beside them — and the second table that outlives a session: usage is what the user consumed,
 * not what their session happened to hold.
 */

// ============================================
// Agent Session
// ============================================

/**
 * `id` is a `uuidv7` string generated by the application (pi re-exports `uuidv7`), not a
 * serial: entry ids and session ids travel through the model's context and the event
 * stream, so they must be opaque and non-enumerable.
 */
export const agentSessions = agentSchema.table(
  "session",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** Stable runtime registry key, e.g. `writing` or `site-assistant`. */
    kind: text("kind").notNull(),
    title: text("title"),
    /**
     * Common LLM settings. Nullable because a different harness may not use a provider model at
     * all; a kind that needs them validates them when constructing its runtime.
     */
    providerId: text("provider_id"),
    modelId: text("model_id"),
    thinkingLevel: text("thinking_level"),
    /** `null` means "every registered tool is active". */
    activeToolNames: jsonb("active_tool_names").$type<string[] | null>(),
    /** Tool tiers the operator pre-approved for this session, e.g. `["draft"]`. */
    autoApprove: jsonb("auto_approve").$type<string[]>().notNull().default([]),
    /** Kind-owned configuration that does not deserve a shared column. */
    runtimeConfig: jsonb("runtime_config")
      .$type<JsonObject>()
      .notNull()
      .default({}),
    /** Schema version for validating and migrating `runtimeConfig`. */
    configVersion: integer("config_version").notNull().default(1),
    /** Active leaf of the session tree. `null` for a fresh session with no entries. */
    leafEntryId: text("leaf_entry_id"),
    /**
     * Lineage of a forked session: the source and the entry the copy started from (`null` for a
     * whole-tree copy). Kept when the source is deleted — the fork stands on its own.
     */
    forkedFromSessionId: text("forked_from_session_id").references(
      (): AnyPgColumn => agentSessions.id,
      { onDelete: "set null" }
    ),
    forkedFromEntryId: text("forked_from_entry_id"),
    ...timestamps,
    ...softDelete,
  },
  (table) => [
    index("agent_session_user_id_idx").on(table.userId),
    index("agent_session_user_kind_idx").on(table.userId, table.kind),
    index("agent_session_deleted_at_idx").on(table.deletedAt),
    index("agent_session_updated_at_idx").on(table.updatedAt),
  ]
);

export type AgentSession = InferSelectModel<typeof agentSessions>;

// ============================================
// Agent Run
// ============================================

export type AgentRunStatus = "active" | "completed" | "cancelled" | "failed";

/**
 * One execution owned by a harness. Keeping runs separate from sessions avoids assuming that every
 * kind uses one long-lived workflow and leaves room for retries, alternate harnesses and sub-runs.
 */
export const agentRuns = agentSchema.table(
  "run",
  {
    id: text("id").primaryKey(),
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    harnessKind: text("harness_kind").notNull(),
    harnessVersion: integer("harness_version").notNull().default(1),
    status: text("status").$type<AgentRunStatus>().notNull().default("active"),
    /** Provider/workflow-owned identifier used to stream, resume or cancel this run. */
    externalRunId: text("external_run_id").notNull(),
    metadata: jsonb("metadata").$type<JsonObject>().notNull().default({}),
    startedAt: timestamp("started_at", { mode: "date" }).defaultNow().notNull(),
    endedAt: timestamp("ended_at", { mode: "date" }),
  },
  (table) => [
    index("agent_run_session_status_idx").on(table.sessionId, table.status),
    uniqueIndex("agent_run_external_id_idx").on(table.externalRunId),
    uniqueIndex("agent_run_one_active_per_session_idx")
      .on(table.sessionId)
      .where(sql`${table.status} = 'active'`),
  ]
);

export type AgentRun = InferSelectModel<typeof agentRuns>;

// ============================================
// Agent Session Entry
// ============================================

/**
 * One node of the session tree. `type`/`payload` mirror a harness's session-entry union
 * (`message`, `compaction`, `modelChange`, `label`, …) rather than being normalised into
 * columns. Storing the payload opaquely lets each harness evolve its entry types without
 * changing the shared table.
 *
 * `seq` is the order entries were persisted in, across every branch; the tree order comes from
 * `parentId`. It is a table-wide `bigserial` taken at insert, not a per-session counter taken
 * at commit, which is only sound because a session has one writer at a time — one active run,
 * and turn acceptance and tree maintenance serialised on the session's advisory lock. Under
 * that invariant "everything persisted before this point" is `seq <= n`, which is how a turn
 * marker cuts the transcript. Gaps are meaningless.
 */
export const agentSessionEntries = agentSchema.table(
  "session_entry",
  {
    seq: bigserial("seq", { mode: "number" }).notNull(),
    id: text("id").notNull(),
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    parentId: text("parent_id"),
    type: text("type").notNull(),
    payload: jsonb("payload").$type<JsonObject>().notNull(),
    timestamp: timestamp("timestamp", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.sessionId, table.id] }),
    index("agent_session_entry_seq_idx").on(table.sessionId, table.seq),
    index("agent_session_entry_parent_idx").on(table.sessionId, table.parentId),
    index("agent_session_entry_type_idx").on(table.sessionId, table.type),
  ]
);

export type AgentSessionEntry = InferSelectModel<typeof agentSessionEntries>;

// ============================================
// Writing Agent State
// ============================================

/**
 * One-to-one extension for the writing agent. Other kinds add sibling extension tables instead of
 * nullable columns to `session`.
 */
export const writingAgentSessions = agentSchema.table(
  "writing_session",
  {
    sessionId: text("session_id")
      .primaryKey()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    targetFeedId: integer("target_feed_id").references(() => feeds.id, {
      onDelete: "set null",
    }),
    /** Feed-level draft fields (slug/type/published/mainImage/…). */
    feedMeta: jsonb("feed_meta").$type<JsonObject>().notNull().default({}),
  },
  (table) => [
    index("writing_agent_session_target_feed_idx").on(table.targetFeedId),
  ]
);

export type WritingAgentSession = InferSelectModel<typeof writingAgentSessions>;

/**
 * Per-locale writing staging buffer. Mirrors `feed_translation` + `content` so `commit_draft` is
 * a near-direct mapping onto `createFeedSchema.translations`.
 */
export const writingAgentDrafts = agentSchema.table(
  "writing_draft",
  {
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    locale: locale("locale").notNull(),
    /** title/excerpt/description/summary — kept as jsonb so adding a field needs no migration. */
    meta: jsonb("meta").$type<JsonObject>().notNull().default({}),
    content: text("content"),
    updatedAt: timestamp("updated_at", { mode: "date" })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => [primaryKey({ columns: [table.sessionId, table.locale] })]
);

export type WritingAgentDraft = InferSelectModel<typeof writingAgentDrafts>;

// ============================================
// Agent Memory
// ============================================

export const AGENT_MEMORY_KIND = {
  /** A page the agent read: URL, title, excerpt. Written automatically by `fetch_url`. */
  Source: "source",
  /** A distilled, cited fact the model chose to keep. */
  Fact: "fact",
  /** A writing preference or lesson extracted from the operator's feedback. */
  Lesson: "lesson",
} as const;

export type AgentMemoryKind =
  (typeof AGENT_MEMORY_KIND)[keyof typeof AGENT_MEMORY_KIND];

export const AGENT_MEMORY_STATUS = {
  Active: "active",
  /** A lesson awaiting the operator's review; never injected into a prompt. */
  Pending: "pending",
  /** Retired by the operator; dropped from the index but kept for provenance. */
  Archived: "archived",
} as const;

export type AgentMemoryStatus =
  (typeof AGENT_MEMORY_STATUS)[keyof typeof AGENT_MEMORY_STATUS];

/**
 * Long-term memory, shared across sessions.
 *
 * `id` is a serial rather than the uuidv7 the other tables use: the RAG pipeline keys
 * `resource_chunk.source_id` as an integer, and only the Root-tier writing agent and the
 * admin dashboard can read a memory, so enumerability buys an attacker nothing.
 *
 * `session_id` is provenance only — it is set to null when the session goes, because the
 * memory is the point and the session is where it happened to come from.
 */
export const agentMemories = agentSchema.table(
  "memory",
  {
    id: serial("id").primaryKey(),
    kind: text("kind").$type<AgentMemoryKind>().notNull(),
    status: text("status")
      .$type<AgentMemoryStatus>()
      .notNull()
      .default(AGENT_MEMORY_STATUS.Active),
    /** One line; what the volatile context and the dashboard list show. */
    title: text("title").notNull(),
    /** Markdown. Chunked and embedded like a post body. */
    content: text("content").notNull(),
    /** Required for a `source`, expected on a `fact`, null on a `lesson`. */
    sourceUrl: text("source_url"),
    sessionId: text("session_id").references(() => agentSessions.id, {
      onDelete: "set null",
    }),
    ...timestamps,
    ...softDelete,
  },
  (table) => [
    /** `fetch_url` upserts on the page URL; the predicate is what `ON CONFLICT` must repeat. */
    uniqueIndex("agent_memory_source_url_idx")
      .on(table.sourceUrl)
      .where(
        sql`${table.kind} = '${sql.raw(AGENT_MEMORY_KIND.Source)}' and ${table.deletedAt} is null`
      ),
    index("agent_memory_session_id_idx").on(table.sessionId),
    index("agent_memory_kind_status_idx").on(table.kind, table.status),
  ]
);

export type AgentMemory = InferSelectModel<typeof agentMemories>;

// ============================================
// Operator configuration
// ============================================

/**
 * The operator's overrides of one agent kind's defaults for *new* sessions. A session copies
 * the effective defaults onto its own row when it is created, so a change here never touches a
 * session that already exists.
 *
 * `kind` matches the host's registry key; there is no row for a kind the process does not
 * serve, and a row for an unregistered kind is inert. The LLM columns are nullable so the
 * definition's own value applies wherever the operator has not chosen; `config` is the kind's
 * own shape, validated by the kind's schema at write time.
 */
export const agentKindConfigs = agentSchema.table("kind_config", {
  kind: text("kind").primaryKey(),
  providerId: text("provider_id"),
  modelId: text("model_id"),
  thinkingLevel: text("thinking_level"),
  /** `null` defers to the definition; a session created with an explicit list still wins. */
  autoApprove: jsonb("auto_approve").$type<string[] | null>(),
  config: jsonb("config").$type<JsonObject>().notNull().default({}),
  updatedAt: timestamp("updated_at", { mode: "date" })
    .defaultNow()
    .notNull()
    .$onUpdate(() => new Date()),
});

export type AgentKindConfig = InferSelectModel<typeof agentKindConfigs>;

/** Sampling parameters an operator may override on a task; every field optional. */
export interface AgentTaskParams {
  maxTokens?: number;
  temperature?: number;
}

/**
 * The operator's overrides of one task — a named, one-shot model call such as the session
 * title or lesson extraction. `task_id` is the host's registry key. `provider_id` and
 * `model_id` are set together or not at all: a task is resolved on the house gateway, never on
 * a caller's own key, so the pair is validated against that catalogue when written.
 */
export const agentTaskConfigs = agentSchema.table("task_config", {
  taskId: text("task_id").primaryKey(),
  providerId: text("provider_id"),
  modelId: text("model_id"),
  /** Replaces the task's default system prompt; `null` restores it. */
  systemPrompt: text("system_prompt"),
  params: jsonb("params").$type<AgentTaskParams>().notNull().default({}),
  updatedAt: timestamp("updated_at", { mode: "date" })
    .defaultNow()
    .notNull()
    .$onUpdate(() => new Date()),
});

export type AgentTaskConfig = InferSelectModel<typeof agentTaskConfigs>;

/** The one `quota_config` row; the table is keyed so a per-tier split is a second row, not a schema change. */
export const AGENT_QUOTA_CONFIG_ID = "default";

/**
 * The operator's usage quota for every caller below `Root`: how much house spend a user may
 * run up per week, and the zone the week is counted in. Both nullable — `null` defers to the
 * code default, like the task and kind rows. The limit is micro-dollars, the ledger's unit.
 */
export const agentQuotaConfigs = agentSchema.table("quota_config", {
  id: text("id").primaryKey(),
  weeklyLimitMicros: bigint("weekly_limit_micros", { mode: "number" }),
  /** An IANA zone; the week resets on its Monday 00:00. */
  resetTimeZone: text("reset_time_zone"),
  updatedAt: timestamp("updated_at", { mode: "date" })
    .defaultNow()
    .notNull()
    .$onUpdate(() => new Date()),
});

export type AgentQuotaConfig = InferSelectModel<typeof agentQuotaConfigs>;

// ============================================
// Agent Tool Approval
// ============================================

export type AgentApprovalStatus = "pending" | "approved" | "rejected";

/**
 * Durable record of a tier-3 approval decision, keyed by the model's `toolCallId`.
 *
 * The in-process runtime resolves approvals through a promise, but that promise dies with
 * the process. Persisting the decision means (a) a reconnecting client sees the resolved
 * state, and (b) the audit trail of "who approved writing to the blog" survives.
 */
export const agentToolApprovals = agentSchema.table(
  "tool_approval",
  {
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    toolCallId: text("tool_call_id").notNull(),
    toolName: text("tool_name").notNull(),
    args: jsonb("args").$type<JsonObject>(),
    status: text("status")
      .$type<AgentApprovalStatus>()
      .notNull()
      .default("pending"),
    comment: text("comment"),
    decidedBy: text("decided_by").references(() => user.id, {
      onDelete: "set null",
    }),
    decidedAt: timestamp("decided_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [primaryKey({ columns: [table.sessionId, table.toolCallId] })]
);

export type AgentToolApproval = InferSelectModel<typeof agentToolApprovals>;

// ============================================
// Usage ledger
// ============================================

/**
 * What produced a ledger row: the turn's own provider calls, or a side job named by what it did.
 * A kind that adds a task adds its name here.
 */
export type AgentUsageSource =
  | "turn"
  | "compaction"
  | "branch_summary"
  | "title"
  | "lessons";

/**
 * One provider call, as billed, attributed to the user it was made for.
 *
 * Every assistant message already carries its usage inside `session_entry.payload`, but that is
 * the wrong place to meter from: entries cascade with their session, so a user who deletes a
 * session would erase what they spent; the payload is opaque and indexed per session, not per
 * user and period; and a side job (title, lesson extraction) has no entry at all. This table
 * holds the same numbers keyed the way a quota reads them, and only `session_id` is severed when
 * the session goes.
 *
 * `cost_micros` is pi's own `usage.cost.total` in micro-dollars — an integer, because a quota
 * is a running sum and floats drift. The token columns are kept for the breakdown, not for
 * metering: a cached read costs a tenth of an uncached one, so raw tokens misprice a long
 * conversation against many short ones.
 *
 * `provider_id` says whose bill it was: the house gateway or a key the caller brought.
 */
export const agentUsageLedger = agentSchema.table(
  "usage_ledger",
  {
    id: bigserial("id", { mode: "number" }).primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    sessionId: text("session_id").references(() => agentSessions.id, {
      onDelete: "set null",
    }),
    runId: text("run_id").references(() => agentRuns.id, {
      onDelete: "set null",
    }),
    /** The tree entry that carries this usage — an assistant message, compaction or branch summary. `null` for a side job. */
    entryId: text("entry_id"),
    kind: text("kind").notNull(),
    source: text("source").$type<AgentUsageSource>().notNull(),
    providerId: text("provider_id").notNull(),
    modelId: text("model_id").notNull(),
    input: integer("input").notNull(),
    output: integer("output").notNull(),
    cacheRead: integer("cache_read").notNull(),
    cacheWrite: integer("cache_write").notNull(),
    /** Subset of `output`; only some providers report it. */
    reasoning: integer("reasoning"),
    costMicros: bigint("cost_micros", { mode: "number" }).notNull(),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    /** The quota read: one user's spend over a period. */
    index("agent_usage_ledger_user_created_idx").on(
      table.userId,
      table.createdAt
    ),
    index("agent_usage_ledger_session_id_idx").on(table.sessionId),
  ]
);

export type AgentUsageLedgerRow = InferSelectModel<typeof agentUsageLedger>;
