import { sql } from "drizzle-orm";
import type { InferSelectModel } from "drizzle-orm";
import {
  bigserial,
  index,
  integer,
  jsonb,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { timestamps, softDelete } from "../libs/common.schema.ts";

import { feeds } from "./contents.schema.ts";
import { locale } from "./enums.ts";
import { pgTable } from "./table.ts";
import { user } from "./user.schema.ts";

/**
 * Persistence for agent sessions.
 *
 * `agent_session` / `agent_session_entry` / `agent_run` / `agent_tool_approval` are **generic** —
 * every agent kind shares them, discriminated by `agent_session.kind`. Writing-specific state
 * lives in `writing_agent_session` and `writing_agent_draft`.
 *
 * The transcript is a **tree**, not a flat log: `agent_session_entry.parentId` points at
 * the previous entry on the branch and `agent_session.leafEntryId` marks the active leaf.
 * That is what lets the agent rewind ("退回三步用另一個角度重寫") and what pi's
 * `SessionStorage` port expects. `@chia/agent-runtime` implements that port over these
 * tables; the writing-specific `writing_agent_draft` belongs to `@chia/agent-writing`.
 *
 * `writing_agent_draft` is the staging buffer: the agent only ever writes here, and a human
 * promotes it into `feed`/`feed_translation`/`content` through the existing
 * `feeds.create`/`feeds.update` procedures.
 */

// ============================================
// Agent Session
// ============================================

/**
 * `id` is a `uuidv7` string generated by the application (pi re-exports `uuidv7`), not a
 * serial: entry ids and session ids travel through the model's context and the event
 * stream, so they must be opaque and non-enumerable.
 */
export const agentSessions = pgTable(
  "agent_session",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** Stable runtime registry key, e.g. `writing` or `site-assistant`. */
    kind: text("kind").notNull(),
    title: text("title"),
    /**
     * Common LLM settings. Nullable because a different harness may not use a provider model at
     * all; a kind that needs them validates them when constructing its runtime.
     */
    providerId: text("provider_id"),
    modelId: text("model_id"),
    thinkingLevel: text("thinking_level"),
    /** `null` means "every registered tool is active". */
    activeToolNames: jsonb("active_tool_names").$type<string[] | null>(),
    /** Tool tiers the operator pre-approved for this session, e.g. `["draft"]`. */
    autoApprove: jsonb("auto_approve").$type<string[]>().notNull().default([]),
    /** Kind-owned configuration that does not deserve a shared column. */
    runtimeConfig: jsonb("runtime_config")
      .$type<Record<string, unknown>>()
      .notNull()
      .default({}),
    /** Schema version for validating and migrating `runtimeConfig`. */
    configVersion: integer("config_version").notNull().default(1),
    /** Active leaf of the session tree. `null` for a fresh session with no entries. */
    leafEntryId: text("leaf_entry_id"),
    ...timestamps,
    ...softDelete,
  },
  (table) => [
    index("agent_session_user_id_idx").on(table.userId),
    index("agent_session_user_kind_idx").on(table.userId, table.kind),
    index("agent_session_deleted_at_idx").on(table.deletedAt),
    index("agent_session_updated_at_idx").on(table.updatedAt),
  ]
);

export type AgentSession = InferSelectModel<typeof agentSessions>;

// ============================================
// Agent Run
// ============================================

export type AgentRunStatus = "active" | "completed" | "cancelled" | "failed";

/**
 * One execution owned by a harness. Keeping runs separate from sessions avoids assuming that every
 * kind uses one long-lived workflow and leaves room for retries, alternate harnesses and sub-runs.
 */
export const agentRuns = pgTable(
  "agent_run",
  {
    id: text("id").primaryKey(),
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    harnessKind: text("harness_kind").notNull(),
    harnessVersion: integer("harness_version").notNull().default(1),
    status: text("status").$type<AgentRunStatus>().notNull().default("active"),
    /** Provider/workflow-owned identifier used to stream, resume or cancel this run. */
    externalRunId: text("external_run_id").notNull(),
    metadata: jsonb("metadata")
      .$type<Record<string, unknown>>()
      .notNull()
      .default({}),
    startedAt: timestamp("started_at", { mode: "date" }).defaultNow().notNull(),
    endedAt: timestamp("ended_at", { mode: "date" }),
  },
  (table) => [
    index("agent_run_session_status_idx").on(table.sessionId, table.status),
    index("agent_run_external_id_idx").on(table.externalRunId),
    uniqueIndex("agent_run_one_active_per_session_idx")
      .on(table.sessionId)
      .where(sql`${table.status} = 'active'`),
  ]
);

export type AgentRun = InferSelectModel<typeof agentRuns>;

// ============================================
// Agent Session Entry
// ============================================

/**
 * One node of the session tree. `type`/`payload` mirror a harness's session-entry union
 * (`message`, `compaction`, `modelChange`, `label`, …) rather than being normalised into
 * columns. Storing the payload opaquely lets each harness evolve its entry types without
 * changing the shared table.
 *
 * `seq` exists so the storage adapter can page entries in insertion order and so the
 * event stream has a stable cursor; the tree order comes from `parentId`.
 */
export const agentSessionEntries = pgTable(
  "agent_session_entry",
  {
    seq: bigserial("seq", { mode: "number" }).notNull(),
    id: text("id").notNull(),
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    parentId: text("parent_id"),
    type: text("type").notNull(),
    payload: jsonb("payload").$type<Record<string, unknown>>().notNull(),
    timestamp: timestamp("timestamp", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.sessionId, table.id] }),
    index("agent_session_entry_seq_idx").on(table.sessionId, table.seq),
    index("agent_session_entry_parent_idx").on(table.sessionId, table.parentId),
    index("agent_session_entry_type_idx").on(table.sessionId, table.type),
  ]
);

export type AgentSessionEntry = InferSelectModel<typeof agentSessionEntries>;

// ============================================
// Writing Agent State
// ============================================

/**
 * One-to-one extension for the writing agent. Other kinds add sibling extension tables instead of
 * nullable columns to `agent_session`.
 */
export const writingAgentSessions = pgTable(
  "writing_agent_session",
  {
    sessionId: text("session_id")
      .primaryKey()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    targetFeedId: integer("target_feed_id").references(() => feeds.id, {
      onDelete: "set null",
    }),
    /** Feed-level draft fields (slug/type/published/mainImage/…). */
    feedMeta: jsonb("feed_meta")
      .$type<Record<string, unknown>>()
      .notNull()
      .default({}),
  },
  (table) => [
    index("writing_agent_session_target_feed_idx").on(table.targetFeedId),
  ]
);

export type WritingAgentSession = InferSelectModel<typeof writingAgentSessions>;

/**
 * Per-locale writing staging buffer. Mirrors `feed_translation` + `content` so `commit_draft` is
 * a near-direct mapping onto `createFeedSchema.translations`.
 */
export const writingAgentDrafts = pgTable(
  "writing_agent_draft",
  {
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    locale: locale("locale").notNull(),
    /** title/excerpt/description/summary — kept as jsonb so adding a field needs no migration. */
    meta: jsonb("meta").$type<Record<string, unknown>>().notNull().default({}),
    content: text("content"),
    updatedAt: timestamp("updated_at", { mode: "date" })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => [primaryKey({ columns: [table.sessionId, table.locale] })]
);

export type WritingAgentDraft = InferSelectModel<typeof writingAgentDrafts>;

// ============================================
// Agent Tool Approval
// ============================================

export type AgentApprovalStatus = "pending" | "approved" | "rejected";

/**
 * Durable record of a tier-3 approval decision, keyed by the model's `toolCallId`.
 *
 * The in-process runtime resolves approvals through a promise, but that promise dies with
 * the process. Persisting the decision means (a) a reconnecting client sees the resolved
 * state, and (b) the audit trail of "who approved writing to the blog" survives.
 */
export const agentToolApprovals = pgTable(
  "agent_tool_approval",
  {
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    toolCallId: text("tool_call_id").notNull(),
    toolName: text("tool_name").notNull(),
    args: jsonb("args").$type<Record<string, unknown>>(),
    status: text("status")
      .$type<AgentApprovalStatus>()
      .notNull()
      .default("pending"),
    comment: text("comment"),
    decidedBy: text("decided_by").references(() => user.id, {
      onDelete: "set null",
    }),
    decidedAt: timestamp("decided_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [primaryKey({ columns: [table.sessionId, table.toolCallId] })]
);

export type AgentToolApproval = InferSelectModel<typeof agentToolApprovals>;
