import type { InferSelectModel } from "drizzle-orm";
import {
  bigserial,
  index,
  integer,
  jsonb,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { timestamps, softDelete } from "../libs/common.schema.ts";

import { feeds } from "./contents.schema.ts";
import { locale } from "./enums.ts";
import { pgTable } from "./table.ts";
import { user } from "./user.schema.ts";

/**
 * Persistence for agent sessions.
 *
 * `agent_session` / `agent_session_entry` / `agent_pending_message` / `agent_tool_approval` are
 * **generic** — every agent kind shares them, discriminated by `agent_session.kind`. `agent_draft`
 * (and `agent_session.targetFeedId` / `feedMeta`) belong to the writing agent specifically; they are
 * nullable, so another kind simply leaves them unset.
 *
 * The transcript is a **tree**, not a flat log: `agent_session_entry.parentId` points at
 * the previous entry on the branch and `agent_session.leafEntryId` marks the active leaf.
 * That is what lets the agent rewind ("退回三步用另一個角度重寫") and what pi's
 * `SessionStorage` port expects. `@chia/agent-core/session` implements that port over these
 * tables; the writing-specific `agent_draft` belongs to `@chia/agent-writing`.
 *
 * `agent_draft` is the staging buffer: the agent only ever writes here, and a human
 * promotes it into `feed`/`feed_translation`/`content` through the existing
 * `feeds.create`/`feeds.update` procedures.
 */

// ============================================
// Agent Session
// ============================================

/**
 * `id` is a `uuidv7` string generated by the application (pi re-exports `uuidv7`), not a
 * serial: entry ids and session ids travel through the model's context and the event
 * stream, so they must be opaque and non-enumerable.
 */
export const agentSessions = pgTable(
  "agent_session",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    /** Reserved for future agent kinds; only `writing` exists today. */
    kind: text("kind").notNull().default("writing"),
    title: text("title"),
    providerId: text("provider_id").notNull(),
    modelId: text("model_id").notNull(),
    thinkingLevel: text("thinking_level").notNull().default("off"),
    /** `null` means "every registered tool is active". */
    activeToolNames: jsonb("active_tool_names").$type<string[] | null>(),
    /** Tool tiers the operator pre-approved for this session, e.g. `["draft"]`. */
    autoApprove: jsonb("auto_approve").$type<string[]>().notNull().default([]),
    /**
     * Feed this session is editing, when it was opened from an existing post. `null` for
     * "write something new" sessions until `commit_draft` runs.
     */
    targetFeedId: integer("target_feed_id").references(() => feeds.id, {
      onDelete: "set null",
    }),
    /** Active leaf of the session tree. `null` for a fresh session with no entries. */
    leafEntryId: text("leaf_entry_id"),
    /**
     * Workflow run driving this session.
     *
     * One long-lived run per session: it waits on a hook for the next message, executes a turn,
     * and parks on an approval hook when a tier-3 tool is gated. Recorded here so a later request
     * can find the run to resume, stream from, or cancel. `null` before the first turn, or after
     * the run completed and a new one has not started.
     */
    workflowRunId: text("workflow_run_id"),
    /** Feed-level draft fields (slug/type/published/mainImage/…). Per-locale fields live on `agent_draft`. */
    feedMeta: jsonb("feed_meta").$type<Record<string, unknown>>(),
    ...timestamps,
    ...softDelete,
  },
  (table) => [
    index("agent_session_user_id_idx").on(table.userId),
    index("agent_session_target_feed_id_idx").on(table.targetFeedId),
    index("agent_session_deleted_at_idx").on(table.deletedAt),
    index("agent_session_updated_at_idx").on(table.updatedAt),
  ]
);

export type AgentSession = InferSelectModel<typeof agentSessions>;

// ============================================
// Agent Session Entry
// ============================================

/**
 * One node of the session tree. `type`/`payload` mirror pi's `SessionTreeEntry` union
 * (`message`, `compaction`, `modelChange`, `label`, …) rather than being normalised into
 * columns — the union is pi's to evolve, and storing it opaquely means a pi upgrade that
 * adds an entry type needs no migration here.
 *
 * `seq` exists so the storage adapter can page entries in insertion order and so the
 * event stream has a stable cursor; the tree order comes from `parentId`.
 */
export const agentSessionEntries = pgTable(
  "agent_session_entry",
  {
    seq: bigserial("seq", { mode: "number" }).notNull(),
    id: text("id").notNull(),
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    parentId: text("parent_id"),
    type: text("type").notNull(),
    payload: jsonb("payload").$type<Record<string, unknown>>().notNull(),
    timestamp: timestamp("timestamp", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.sessionId, table.id] }),
    index("agent_session_entry_seq_idx").on(table.sessionId, table.seq),
    index("agent_session_entry_parent_idx").on(table.sessionId, table.parentId),
    index("agent_session_entry_type_idx").on(table.sessionId, table.type),
  ]
);

export type AgentSessionEntry = InferSelectModel<typeof agentSessionEntries>;

// ============================================
// Agent Draft
// ============================================

/**
 * Per-locale staging buffer. Mirrors `feed_translation` + `content` so `commit_draft` is
 * a near-direct mapping onto `createFeedSchema.translations`.
 */
export const agentDrafts = pgTable(
  "agent_draft",
  {
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    locale: locale("locale").notNull(),
    /** title/excerpt/description/summary — kept as jsonb so adding a field needs no migration. */
    meta: jsonb("meta").$type<Record<string, unknown>>().notNull().default({}),
    content: text("content"),
    updatedAt: timestamp("updated_at", { mode: "date" })
      .defaultNow()
      .notNull()
      .$onUpdate(() => new Date()),
  },
  (table) => [primaryKey({ columns: [table.sessionId, table.locale] })]
);

export type AgentDraft = InferSelectModel<typeof agentDrafts>;

// ============================================
// Agent Pending Message
// ============================================

/**
 * Steering / follow-up queue.
 *
 * `AgentHarness.steer()` is a method, not a callback, so a message that arrives over HTTP
 * mid-turn cannot reach the running harness directly. The transport writes a row here and
 * the turn drains it at pi's queue drain points. Rows are kept (not deleted) after
 * `consumedAt` so the transcript can explain why the agent changed course.
 */
export const agentPendingMessages = pgTable(
  "agent_pending_message",
  {
    id: text("id").primaryKey(),
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    /** `steer` interrupts the current turn; `followUp` waits until it would otherwise stop. */
    kind: text("kind").notNull(),
    text: text("text").notNull(),
    consumedAt: timestamp("consumed_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    index("agent_pending_message_pending_idx").on(
      table.sessionId,
      table.consumedAt
    ),
  ]
);

export type AgentPendingMessage = InferSelectModel<typeof agentPendingMessages>;

// ============================================
// Agent Tool Approval
// ============================================

/**
 * Durable record of a tier-3 approval decision, keyed by the model's `toolCallId`.
 *
 * The in-process runtime resolves approvals through a promise, but that promise dies with
 * the process. Persisting the decision means (a) a reconnecting client sees the resolved
 * state, and (b) the audit trail of "who approved writing to the blog" survives.
 */
export const agentToolApprovals = pgTable(
  "agent_tool_approval",
  {
    sessionId: text("session_id")
      .notNull()
      .references(() => agentSessions.id, { onDelete: "cascade" }),
    toolCallId: text("tool_call_id").notNull(),
    toolName: text("tool_name").notNull(),
    args: jsonb("args").$type<Record<string, unknown>>(),
    approved: text("approved"),
    comment: text("comment"),
    decidedBy: text("decided_by").references(() => user.id, {
      onDelete: "set null",
    }),
    decidedAt: timestamp("decided_at", { mode: "date" }),
    createdAt: timestamp("created_at", { mode: "date" }).defaultNow().notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.sessionId, table.toolCallId] }),
    uniqueIndex("agent_tool_approval_call_idx").on(table.toolCallId),
  ]
);

export type AgentToolApproval = InferSelectModel<typeof agentToolApprovals>;
