import { IsString, IsArray, IsOptional } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";

export class AuthorizeSpotifyDto {
  @IsString()
  @ApiProperty({
    nullable: false,
    required: true,
    description: "The state to pass to Spotify, generated by the client",
  })
  state: string;

  @IsArray()
  @ApiProperty({
    nullable: false,
    required: true,
    description: "The scopes to request from Spotify",
  })
  scopes: string[];

  @IsString()
  @IsOptional()
  @ApiProperty({
    nullable: true,
    required: false,
    description:
      "The context can be stored in the service and passed back to the client",
  })
  context?: string;
}

export class AuthorizeCodeDto {
  @IsString()
  @ApiProperty({
    nullable: false,
    required: true,
    description: "The code returned by Spotify",
  })
  code: string;

  @IsString()
  @ApiProperty({
    nullable: false,
    required: true,
    description: "The state returned by Spotify",
  })
  state: string;
}
