name: backend Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]
    paths:
      - "apps/backend/**"
      - "packages/db/**"
      - ".github/workflows/backend-docker-ci.yml"
      - "package.json"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  PNPM_VERSION: 8.4.0
  NODE_VERSION: 18.*
  GIT_HASH: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ contains(github.event.pull_request.labels.*.name, 'backend:docker') || contains(github.event.pull_request.labels.*.name, 'backend:enhancement') }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Builder
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: false
          load: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chia1104-backend:${{ env.GIT_HASH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DATABASE_URL=${{ env.DATABASE_URL }}
            TURBO_TEAM=${{ env.TURBO_TEAM }}
            TURBO_TOKEN=${{ env.TURBO_TOKEN }}
