name: Docker CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened, edited, labeled, unlabeled, ready_for_review ]
    paths-ignore:
      - "**.md"
      - "**.mdx"
      - "posts/**"
      - "public/**"
      - "cypress/**"
      - "**.config.js"

env:
  NEXT_PUBLIC_FORMSPREE_KEY: ${{ secrets.NEXT_PUBLIC_FORMSPREE_KEY }}
  GH_PUBLIC_TOKEN: ${{ secrets.GH_PUBLIC_TOKEN }}
  NEXT_PUBLIC_RE_CAPTCHA_KEY: ${{ secrets.NEXT_PUBLIC_RE_CAPTCHA_KEY }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  PNPM_VERSION: 7.15.0
  NODE_VERSION: 16.*
  GIT_HASH: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event.pull_request.labels && contains('docker,enhancement', join(github.event.pull_request.labels.*.name, ',')) }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Builder
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chia1104:${{ env.GIT_HASH }}
          build-args: |
            NEXT_PUBLIC_FORMSPREE_KEY=${{ env.NEXT_PUBLIC_FORMSPREE_KEY }}
            GH_PUBLIC_TOKEN=${{ env.GH_PUBLIC_TOKEN }}
            NEXT_PUBLIC_RE_CAPTCHA_KEY=${{ env.NEXT_PUBLIC_RE_CAPTCHA_KEY }}
            GOOGLE_API_KEY=${{ env.GOOGLE_API_KEY }}
            SPOTIFY_CLIENT_ID=${{ env.SPOTIFY_CLIENT_ID }}
            SPOTIFY_CLIENT_SECRET=${{ env.SPOTIFY_CLIENT_SECRET }}
#      - name: Test
#        run: |
#          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/chia1104:${{ env.GIT_HASH }}
