name: Web CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Unit tests - Vitest
        run: pnpm test:vitest

      - name: Build
        run: pnpm build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build
  e2e-on-chrome:
    name: E2E on Chrome
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome

  e2e-on-firefox:
    needs: build
    runs-on: ubuntu-latest
    name: E2E on Firefox
    timeout-minutes: 15
    container:
      image: cypress/browsers:node16.13.2-chrome100-ff98
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: firefox
