name: Web CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Unit tests - Vitest
        run: pnpm test:vitest

      - name: E2E Chrome
      - uses: cypress-io/github-action@v2
        with:
          start: pnpm dev
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome

      - name: E2E Firefox
      - uses: cypress-io/github-action@v2
        with:
          start: pnpm dev
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: firefox

      - name: Build
        run: pnpm build
