name: Web CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, synchronize]

env:
  NEXT_PUBLIC_FORMSPREE_KEY: ${{ secrets.NEXT_PUBLIC_FORMSPREE_KEY }}
  GH_PUBLIC_TOKEN: ${{ secrets.GH_PUBLIC_TOKEN }}
  NEXT_PUBLIC_RE_CAPTCHA_KEY: ${{ secrets.NEXT_PUBLIC_RE_CAPTCHA_KEY }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  PNPM_VERSION: 7.5.1

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16.*, 18.* ]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Unit tests - Vitest
        run: pnpm test:vitest

      - name: Build
        run: pnpm build

#      - name: Save build folder
#        uses: actions/upload-artifact@v3
#        with:
#          name: build
#          if-no-files-found: error
#          path: .next

      - name: E2E on Chrome
        uses: cypress-io/github-action@v4
        with:
          start: pnpm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          record: false
          env:
            NEXT_PUBLIC_FORMSPREE_KEY: ${{ env.NEXT_PUBLIC_FORMSPREE_KEY }}
            GH_PUBLIC_TOKEN: ${{ env.GH_PUBLIC_TOKEN }}
            NEXT_PUBLIC_RE_CAPTCHA_KEY: ${{ env.NEXT_PUBLIC_RE_CAPTCHA_KEY }}
            GOOGLE_API_KEY: ${{ env.GOOGLE_API_KEY }}
            SPOTIFY_CLIENT_ID: ${{ env.SPOTIFY_CLIENT_ID }}
            SPOTIFY_CLIENT_SECRET: ${{ env.SPOTIFY_CLIENT_SECRET }}

      - name: E2E on Edge
        uses: cypress-io/github-action@v4
        with:
          start: pnpm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: edge
          record: false
          env:
            NEXT_PUBLIC_FORMSPREE_KEY: ${{ env.NEXT_PUBLIC_FORMSPREE_KEY }}
            GH_PUBLIC_TOKEN: ${{ env.GH_PUBLIC_TOKEN }}
            NEXT_PUBLIC_RE_CAPTCHA_KEY: ${{ env.NEXT_PUBLIC_RE_CAPTCHA_KEY }}
            GOOGLE_API_KEY: ${{ env.GOOGLE_API_KEY }}
            SPOTIFY_CLIENT_ID: ${{ env.SPOTIFY_CLIENT_ID }}
            SPOTIFY_CLIENT_SECRET: ${{ env.SPOTIFY_CLIENT_SECRET }}
