name: "www Next.js Bundle Analysis"

on:
  pull_request:
  push:
    branches:
      - develop # change this if your default branch is named differently
  workflow_dispatch:

defaults:
  run:
    # change this if your nextjs app does not live at the root of the repo
    working-directory: ./

env:
  GH_PUBLIC_TOKEN: ${{ secrets.GH_PUBLIC_TOKEN }}
  NEXT_PUBLIC_RE_CAPTCHA_KEY: ${{ secrets.NEXT_PUBLIC_RE_CAPTCHA_KEY }}
  RE_CAPTCHA_KEY: ${{ secrets.RE_CAPTCHA_KEY }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
  SPOTIFY_FAVORITE_PLAYLIST_ID: ${{ secrets.SPOTIFY_FAVORITE_PLAYLIST_ID }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  SHA_256_HASH: ${{ secrets.SHA_256_HASH }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  NODE_VERSION: 20
  GIT_HASH: ${{ github.sha }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  NEXT_PUBLIC_UMAMI_WEBSITE_ID: ${{ secrets.NEXT_PUBLIC_UMAMI_WEBSITE_ID }}
  NEXT_PUBLIC_UMAMI_URL: ${{ secrets.NEXT_PUBLIC_UMAMI_URL }}
  UMAMI_DB_URL: ${{ secrets.UMAMI_DB_URL }}
  UMAMI_EDGE_DB_URL: ${{ secrets.UMAMI_EDGE_DB_URL }}
  NEXT_PUBLIC_GISCUS_REPO_ID: ${{ secrets.NEXT_PUBLIC_GISCUS_REPO_ID }}
  NEXT_PUBLIC_GISCUS_CATEGORY_ID: ${{ secrets.NEXT_PUBLIC_GISCUS_CATEGORY_ID }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  UPSTASH_TOKEN: ${{ secrets.UPSTASH_TOKEN }}
  CACHE_PROVIDER: upstash
  NODE_ENV: test
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  AUTH_URL: http://localhost:3000
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  BETA_DATABASE_URL: ${{ secrets.BETA_DATABASE_URL }}
  ADMIN_ID: ${{ secrets.ADMIN_ID }}
  BETA_ADMIN_ID: ${{ secrets.BETA_ADMIN_ID }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  NEXT_PUBLIC_ENV: beta
  TURBO_TELEMETRY_DISABLED: 1
  INTERNAL_SERVICE_ENDPOINT: ${{ secrets.INTERNAL_SERVICE_ENDPOINT }}
  NEXT_PUBLIC_SERVICE_ENDPOINT: ${{ secrets.NEXT_PUBLIC_SERVICE_ENDPOINT }}

concurrency:
  group: pull-${{ github.ref }}-www-bundle-analysis
  cancel-in-progress: true

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: "🐙️  Checkout"
        id: pull-checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: "📦  Install"
        id: pull-install
        uses: "./.github/actions/install"
        with:
          NODE_VERSION: ${{ env.NODE_VERSION }}

      - name: "📦  Next.js cache"
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/apps/www/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-www

      - name: Build next.js app
        run: pnpm build:www

      - name: Analyze bundle
        run: cd apps/www && npx -p nextjs-bundle-analysis report

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: app/www/.next/analyze/__bundle_analysis.json

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: success() && github.event.number
        with:
          workflow: nextjs_bundle_analysis.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: app/www/.next/analyze/base

      # And here's the second place - this runs after we have both the current and
      # base branch bundle stats, and will compare them to determine what changed.
      # There are two configurable arguments that come from package.json:
      #
      # - budget: optional, set a budget (bytes) against which size changes are measured
      #           it's set to 350kb here by default, as informed by the following piece:
      #           https://infrequently.org/2021/03/the-performance-inequality-gap/
      #
      # - red-status-percentage: sets the percent size increase where you get a red
      #                          status indicator, defaults to 20%
      #
      # Either of these arguments can be changed or removed by editing the `nextBundleAnalysis`
      # entry in your package.json file.
      - name: Compare with base branch bundle
        if: success() && github.event.number
        run: ls -laR app/www/.next/analyze/base && npx -p nextjs-bundle-analysis compare

      - name: Get Comment Body
        id: get-comment-body
        if: success() && github.event.number
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat .next/analyze/__bundle_analysis_comment.txt)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "<!-- __NEXTJS_BUNDLE -->"

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v2
        if: success() && github.event.number && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v2
        if: success() && github.event.number && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
